"""add offence name

Revision ID: 8cf7c4f4c9e4
Revises: a7f898d9954e
Create Date: 2024-12-26 00:19:14.378550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf7c4f4c9e4'
down_revision = 'a7f898d9954e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint('unique', ['name'])
        batch_op.drop_column('code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
