"""add payment_offender_offence relationship

Revision ID: d67503097646
Revises: 8cf7c4f4c9e4
Create Date: 2024-12-26 01:24:46.475053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67503097646'
down_revision = '8cf7c4f4c9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offender_offence_id', sa.Integer(), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('offender_offence_relationship', 'offender_offence', ['offender_offence_id'], ['id'])
        batch_op.drop_column('offender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offender_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'offender', ['offender_id'], ['id'])
        batch_op.drop_column('offender_offence_id')

    # ### end Alembic commands ###
